# Generated by Django 3.0.8 on 2020-07-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('value', models.DecimalField(decimal_places=2, help_text='Valor de aquisição', max_digits=8, verbose_name='Valor')),
                ('acquisition_date', models.DateField(verbose_name='Data de aquisição')),
                ('description', models.TextField(verbose_name='descrição')),
            ],
        ),
    ]
