# Generated by Django 3.0.8 on 2020-07-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20200726_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonio',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de aquisição'),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='acquisition_document_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Nota Fiscal de aquisição'),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='description',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor de aquisição', max_digits=8, null=True, verbose_name='Valor'),
        ),
    ]
