# Generated by Django 3.0.8 on 2020-07-27 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20200726_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Descrição')),
                ('hd_size', models.IntegerField(blank=True, null=True, verbose_name='Capacidade de armazenamento HD(GB)')),
                ('hd_type', models.CharField(blank=True, choices=[(1, 'HDD'), (2, 'SSD')], max_length=1, null=True, verbose_name='Tipo de HD')),
                ('memory_size', models.IntegerField(blank=True, null=True, verbose_name='Tamanho da memória(GB)')),
                ('processor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Processador')),
                ('os', models.CharField(blank=True, max_length=30, null=True, verbose_name='Sistema operacional')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.AlterModelOptions(
            name='patrimonio',
            options={'verbose_name': 'Patrimônio', 'verbose_name_plural': 'Patrimônios'},
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='date_term',
            field=models.DateField(blank=True, null=True, verbose_name='Data de registro do termo'),
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de série'),
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='term',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Termo de responsabilidade'),
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='term_expires_at',
            field=models.DateField(blank=True, null=True, verbose_name='Termo expira em '),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.Tipo'),
        ),
    ]
