# Generated by Django 3.0.8 on 2020-07-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20200726_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='description',
            field=models.CharField(help_text='Deixar os detalhes em branco, caso não seja um computador', max_length=50, verbose_name='Descrição'),
        ),
    ]
